### PR TITLE
See desc, 4 tasks were done

### PR DESCRIPTION
**Pull request by UkrainianEagleOwl**
Added change and delete record from address book.
Added new two fields classes.
Added this new classes in record and all record functions that touch this fields, Change the commands that use record. Added using notes classes and commands.
Remake all main for more useful using commands.
Add new greet.
Add new check for fields.

### CODE REVIEW

**Comment by leegosx** [comment]
ого, як багато всього) одобряю!🙌🏻

**Comment by leegosx** [comment]
/

**Review by leegosx — APPROVED** [review]

**Comment by leegosx** [comment]
nice

**Review by leegosx — APPROVED** [review]

**Review by Adentas — APPROVED** [review]
Перевірив, видимих помилок не виявлено

**Pull request merged**
